"use client";
import {useState} from 'react';
import {Search,ArrowUpRight,Plus,Layers3} from 'lucide-react';
import Link from '@/components/site-link';
import {Input} from '@/components/ui/input';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Bilingual,useI18n} from '@/components/i18n';
import {usageLabels,kindLabels,type ModEntry} from '@/lib/mod-types';
export function UsageBadge({value}:{value:string}){const {locale}=useI18n();return <span className={'status '+(value==='active'?'retained':['paused','retired'].includes(value)?'paused':value==='repair'?'repair':'testing')}>{(usageLabels[value]||[value,value])[locale==='en'?1:0]}</span>}
export function ModLibrary({entries}:{entries:ModEntry[]}){const {locale}=useI18n(),l=(z:string,e:string)=>locale==='en'?e:z;const [query,setQuery]=useState(''),[status,setStatus]=useState('all'),[source,setSource]=useState('all');const items=entries.filter(m=>(status==='all'||m.usage_status===status)&&(source==='all'||m.origin===source)&&[m.title,m.title_en,m.author,m.summary,m.summary_en,m.mod_code].join(' ').toLowerCase().includes(query.toLowerCase()));return <>
<div className="mod-controls mod-catalog-notice"><Link className="button primary" href="/submit/mod"><Plus size={17}/>{l('提交 Mod','Submit a mod')}</Link><Link className="button" href="/submissions">{l('管理我的作品','Manage my creations')}</Link><p className="bilingual-note">{l('资料收录 ≠ 当前版本实测。请查看状态、依赖与来源。','A catalog entry is not a current-version test certification. Check its status, dependencies and source.')}</p></div>
<div className="library-layout"><aside className="library-sidebar"><p className="eyebrow">FILTER / DISCOVER</p><h2>{l('Mod 状态','Usage status')}</h2>{['all',...new Set(entries.map(m=>m.usage_status))].map(s=><button type="button" className={s===status?'active':''} key={s} onClick={()=>setStatus(s)} aria-pressed={s===status}>{s==='all'?l('全部','All'):usageLabels[s]?.[locale==='en'?1:0]}<span>{entries.filter(m=>s==='all'||m.usage_status===s).length}</span></button>)}<Select value={source} onValueChange={setSource}><SelectTrigger aria-label={l('资料来源','Catalog source')}><SelectValue/></SelectTrigger><SelectContent>{[['all','全部来源','All sources'],['stalingrad','斯大林格勒','Stalingrad'],['github','GitHub 项目','GitHub projects'],['community','社区投稿','Community']].map(([v,z,e])=><SelectItem key={v} value={v}>{l(z,e)}</SelectItem>)}</SelectContent></Select><p>{l('暂停、弃用项目保留为历史档案；GitHub 项目独立收录，不代表已加入斯大林格勒。','Paused and retired entries remain as history. GitHub projects are independent, not automatically enabled in Stalingrad.')}</p></aside>
<section className="library-main"><div className="library-top"><div className="search-input"><Search size={18}/><Input value={query} onChange={e=>setQuery(e.target.value)} aria-label={l('搜索 Mod','Search mods')} placeholder={l('搜索名称、功能、作者或 Mod 码…','Search titles, features, authors or Mod codes…')}/></div><span>{items.length} {l('项资料','entries')}</span></div><div className="mod-grid">{items.map(m=><article className="mod-card" key={m.id}><div className="mod-card-head"><span className="mod-index">{kindLabels[m.kind]?.[locale==='en'?1:0]}</span><UsageBadge value={m.usage_status}/></div><h3><Link href={'/mods/'+m.id}><Bilingual zh={m.title} en={m.title_en}/></Link></h3><p><Bilingual zh={m.summary} en={m.summary_en}/></p><p className="mod-source">{m.author}</p><div className="mod-card-footer"><span className="source-pill">{m.origin==='github'?'GitHub':m.origin==='stalingrad'?'Stalingrad':'Community'}</span><Link href={'/mods/'+m.id} className="text-link">{l('查看资料','Explore')}<ArrowUpRight size={16}/></Link></div>{m.editable&&<div className="mod-manage-actions"><Link className="text-link" href={'/mods/'+m.id+'/edit'}>{l('编辑资料与 Mod 码','Edit details & Mod codes')}</Link></div>}</article>)}</div>{!items.length&&<div className="empty-surface"><Layers3 size={30}/><h2>{l('没有匹配的 Mod','No matching mods')}</h2><button className="button" onClick={()=>{setQuery('');setStatus('all');setSource('all')}}>{l('清除筛选','Clear filters')}</button></div>}<div className="workbench-footnote"><p>{l('想调整基础单位？','Want to rebalance units?')} <Link className="text-link" href="/workbench">{l('打开 Mod 工作台 →','Open the Mod workbench →')}</Link></p></div></section></div></>}
