// Intentionally empty by default.
// Add Drizzle tables here when the site actually needs a database.
// See examples/d1/db/schema.ts for an opt-in example.
import { sqliteTable, text, integer, index } from "drizzle-orm/sqlite-core";
export const maps = sqliteTable("maps", {
 id:text("id").primaryKey(), ownerId:text("owner_id").notNull(), author:text("author").notNull(), title:text("title").notNull(), summary:text("summary").notNull(), description:text("description").notNull(), gameVersion:text("game_version").notNull(), players:integer("players").notNull(), category:text("category").notNull(), mods:text("mods").notNull(), mapCode:text("map_code").notNull().default(""), status:text("status").notNull().default("pending"), fileName:text("file_name").notNull(), fileKey:text("file_key").notNull(), fileSize:integer("file_size").notNull(), sha256:text("sha256").notNull(), coverKey:text("cover_key"), coverType:text("cover_type"), createdAt:text("created_at").notNull(), reviewedAt:text("reviewed_at"), feedback:text("feedback").notNull().default(""), revision:integer("revision").notNull().default(0), reviewToken:text("review_token")
},t=>[index("idx_maps_status_created").on(t.status,t.createdAt),index("idx_maps_owner_created").on(t.ownerId,t.createdAt)]);
export const reviews = sqliteTable("reviews",{id:text("id").primaryKey(),mapId:text("map_id").notNull().references(()=>maps.id),reviewerId:text("reviewer_id").notNull(),action:text("action").notNull(),feedback:text("feedback").notNull(),checklist:text("checklist").notNull(),createdAt:text("created_at").notNull()},t=>[index("idx_reviews_map").on(t.mapId,t.createdAt)]);
export const featuredMaps = sqliteTable("featured_maps", {
 id:text("id").primaryKey(),body:text("body").notNull(),revision:integer("revision").notNull().default(0),updatedAt:text("updated_at").notNull(),updatedBy:text("updated_by").notNull(),
 fileKey:text("file_key"),fileName:text("file_name").notNull().default(""),fileSize:integer("file_size").notNull().default(0),sha256:text("sha256").notNull().default(""),coverKey:text("cover_key"),coverType:text("cover_type")
});
export const communityMods=sqliteTable('community_mods',{
 id:text('id').primaryKey(),ownerId:text('owner_id'),origin:text('origin').notNull(),body:text('body').notNull(),status:text('status').notNull().default('pending'),revision:integer('revision').notNull().default(0),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),feedback:text('feedback').notNull().default(''),fileKey:text('file_key'),fileName:text('file_name').notNull().default(''),fileSize:integer('file_size').notNull().default(0),sha256:text('sha256').notNull().default(''),reviewToken:text('review_token')
},t=>[index('idx_mods_owner_status').on(t.ownerId,t.status),index('idx_mods_status_created').on(t.status,t.createdAt)]);
export const modReviews=sqliteTable('mod_reviews',{id:text('id').primaryKey(),modId:text('mod_id').notNull().references(()=>communityMods.id),reviewerId:text('reviewer_id').notNull(),action:text('action').notNull(),feedback:text('feedback').notNull(),checklist:text('checklist').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_mod_reviews_mod').on(t.modId,t.createdAt)]);
